import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import { GoogleAuthProvider } from './googleAuth'
import { ReduxProvider } from './provider'

const inter = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'DineVoyage',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={`${inter.className}`}>
                <GoogleAuthProvider>
                    <ReduxProvider>
                        {children}
                    </ReduxProvider>
                </GoogleAuthProvider>
            </body>
        </html>
    )
}
